name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted   # atau ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: |
          for i in 1 2 3 4 5; do
            echo "Attempt $i login..."
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
            if [ $? -eq 0 ]; then break; fi
            sleep 10
          done

      - name: Build and push image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/laravel-app:latest -t ${{ secrets.DOCKER_USERNAME }}/laravel-app:${{ github.sha }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/laravel-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/laravel-app:${{ github.sha }}

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /var/www/techease
            docker compose pull app
            docker compose up -d --force-recreate --remove-orphans app
            sleep 5
            docker compose exec -T app php artisan migrate --force
            docker compose exec -T app php artisan config:cache
            docker compose exec -T app php artisan route:cache
            docker compose exec -T app php artisan view:cache
            docker compose restart nginx
            docker image prune -af
