name: Deploy to Production

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted   # <-- INI PENTING

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DockerHub_TOKEN }}

      - name: Build and push app image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/laravel-app:latest
            ${{ secrets.DOCKER_USERNAME }}/laravel-app:${{ github.sha }}

      - name: Deploy to Server (Local Runner)
        run: |
          set -e
          cd /var/www/techease
          docker compose pull app
          docker compose down || true
          docker compose up -d
          docker image prune -f
          echo "✅ Deploy selesai!"
